version: '2'
services:
  blg-admin:
    image: blg/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  blg-api:
    image: blg/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev